### ISSUE TITLE
Add Laravel 8 Support

### ISSUE THREAD

**Issue by squatto** [stephenjude/default-model-sorting#2]
Do you have any plans to update this package to support Laravel 8? I can submit a PR if you'd like and if you would have some time soon to review it. Thanks!

**Comment by stephenjude** [comment]
I just saw this after merging the L8 support PR. Thanks

**Comment by squatto** [comment]
You're welcome! Thanks for jumping on that change 👍🏻

**Comment by jonnott** [comment]
@stephenjude PR to bring this into the core framework in L9.x https://github.com/laravel/framework/pull/40892

**Comment by stephenjude** [comment]
@jonnott go ahead

**Comment by stephenjude** [comment]
Done, let me know if it works fine: https://github.com/stephenjude/default-model-sorting/releases/tag/2.0.0
